apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: portfolio
type: Opaque
stringData:
  MONGO_ROOT_USER: admin
  MONGO_ROOT_PASSWORD: "PortfolioAlia2026!"
  MONGO_DATABASE: portfolio_alia
  MONGODB_URI: "mongodb://admin:PortfolioAlia2026!@mongodb:27017/portfolio_alia?authSource=admin"
